# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'salesforcePOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for salesforcePOC

  target 'salesforcePOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'salesforcePOCUITests' do
    # Pods for testing
  end

  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.1.0'
  pod 'SVProgressHUD'
  pod 'ObjectMapper'

end
